import json
import os

INPUT_FILE = r"C:\Users\KT156S\.gemini\antigravity-ide\brain\f8ab7991-e804-4ad8-879b-c29d7b803e76\scratch\comments.json"
OUTPUT_FILE = r"C:\Users\KT156S\.gemini\antigravity-ide\brain\f8ab7991-e804-4ad8-879b-c29d7b803e76\scratch\comments_translated.json"

TRANSLATIONS = {
    # General / ReportLab presentation comments
    "Navy": "Bleu marine",
    "Header (on all pages except page 1)": "En-tête (sur toutes les pages sauf la page 1)",
    "Footer (on all pages)": "Pied de page (sur toutes les pages)",
    "Slate Gray": "Gris ardoise",
    "Setup document": "Configurer le document",
    "Styles": "Styles",
    "Custom styles": "Styles personnalisés",
    "Colors": "Couleurs",
    "Read and parse markdown": "Lire et analyser le markdown",
    "Skip empty lines if they are not formatting placeholders": "Ignorer les lignes vides si ce ne sont pas des espaces de formatage",
    "Title (# )": "Titre (# )",
    "Add a decorative line under the title": "Ajouter une ligne décorative sous le titre",
    "Section (## )": "Section (## )",
    "Conseils section (special)": "Section Conseils (spécial)",
    "Question (### Q : or ###)": "Question (### Q : ou ###)",
    "Answer (**R :** or **R:** or simply starting with it)": "Réponse (**R :** ou **R:** ou commençant simplement par cela)",
    "Clean up the prefix markdown": "Nettoyer le markdown du préfixe",
    "Add bold R: back in HTML style": "Réintégrer le R: en gras au format HTML",
    "Format inline bold markdown to HTML <b>": "Formater le markdown en gras en ligne en HTML <b>",
    "Bullet points inside Q&A or standard lists": "Puces dans les questions-réponses ou listes standard",
    "Format markdown bold/italic": "Formater le markdown en gras/italique",
    "Use appropriate style": "Utiliser le style approprié",
    "Horizontal rules": "Règles horizontales",
    "Regular text or paragraphs": "Texte normal ou paragraphes",
    "Check if this text belongs to a link or special formatting": "Vérifier si ce texte appartient à un lien ou à un formatage spécial",
    "If we were reading intro text": "Si nous étions en train de lire le texte d'introduction",
    "Build document": "Construire le document",
    "Format relative time from publishedAt date": "Formater le temps relatif à partir de la date publishedAt",
    "Map typeBailleur to a readable label": "Associer typeBailleur à un libellé lisible",
    "Grid lines": "Lignes de grille",
    "Area under the path": "Zone sous le chemin",
    "Path Line": "Ligne de chemin",
    "Markers": "Marqueurs",
    "Tooltip Overlay": "Superposition d'info-bulle",
    "X Axis Labels": "Étiquettes de l'axe X",
    "Main KPI Stat Cards": "Cartes des principales statistiques KPI",
    "Beautiful Performance Graphs Section": "Section des graphiques de performance",
    "Recent Visits & Partners Grid": "Grille des visites récentes & partenaires",
    "Ensure it scales nicely even with low values": "S'assurer que l'échelle s'adapte bien même avec des valeurs faibles",
    "Calculate smooth Bezier Curve": "Calculer une courbe de Bézier lisse",
    "Search + Status Dropdown Row": "Ligne de recherche + menu déroulant des statuts",
    "Search bar": "Barre de recherche",
    "Custom Dropdown": "Menu déroulant personnalisé",
    "Dropdown Menu": "Menu déroulant",
    "Dropdown animation keyframes": "Images clés de l'animation du menu déroulant",
    "Close dropdown on outside click": "Fermer le menu déroulant en cas de clic à l'extérieur",
    "Status filter": "Filtre de statut",
    "Search filter": "Filtre de recherche",
    "Count by status": "Compter par statut",
    "Success notification": "Notification de succès",
    "Sidebar Tabs": "Onglets de la barre latérale",
    "Content Area": "Zone de contenu",
    "Profile Tab": "Onglet Profil",
    "Security Tab": "Onglet Sécurité",
    "Notifications Tab": "Onglet Notifications",
    "Business Rules Tab": "Onglet Règles de gestion",
    "Max Active Listings": "Nombre maximum d'annonces actives",
    "Max Photos Per Listing": "Nombre maximum de photos par annonce",
    "Info Card": "Carte d'information",
    "Profile state": "État du profil",
    "Password state": "État du mot de passe",
    "Notifications preferences": "Préférences des notifications",
    "Business rules state": "État des règles de gestion",
    "Update state": "Mettre à jour l'état",
    "Adjust for production": "Ajuster pour la production",
    "Socket.io connection": "Connexion Socket.io",
    "Middleware to inject prisma and io into requests": "Middleware pour injecter prisma et io dans les requêtes",
    "Basic route": "Route de base",
    "Swagger Documentation": "Documentation Swagger",
    "Import and use routes": "Importer et utiliser les routes",
    "Import visit controller for automatic 72-hour expiration logic": "Importer le contrôleur de visites pour la logique d'expiration automatique sous 72h",
    "Run expiration check immediately on start and then every 60 seconds": "Exécuter le contrôle d'expiration immédiatement au démarrage, puis toutes les 60 secondes",
    "Scan routes and controllers for JSDoc": "Scanner les routes et contrôleurs pour JSDoc",
    "Helper to format property URLs (same as in propertyController)": "Fonction d'aide pour formater les URL de propriétés (comme dans propertyController)",
    "Calculate sum of rents of published properties": "Calculer la somme des loyers des propriétés publiées",
    "Fetch recent visits": "Récupérer les visites récentes",
    "Today's metrics": "Métriques du jour",
    "Last 7 days daily stats for graphs": "Statistiques quotidiennes des 7 derniers jours pour les graphiques",
    "Create a notification for all users with the LOCATAIRE role": "Créer une notification pour tous les utilisateurs ayant le rôle LOCATAIRE",
    "Delete photos": "Supprimer les photos",
    "Delete demands of visits": "Supprimer les demandes de visites",
    "Delete the annonce itself": "Supprimer l'annonce elle-même",
    "Delete the associated bien & address": "Supprimer le bien et l'adresse associés",
    "'password' from frontend, mapped to 'motDePasse' in DB": "'password' du frontend, mappé à 'motDePasse' dans la BD",
    "Append token to deep link": "Ajouter le jeton au lien profond",
    "For security, don't disclose that the email does not exist": "Par sécurité, ne pas divulguer que l'email n'existe pas",
    "Token expires in 1 hour. Signed with process.env.JWT_SECRET + user.motDePasse": "Le jeton expire dans 1 heure. Signé avec process.env.JWT_SECRET + user.motDePasse",
    "Renders a premium, stunning UI for resetting password": "Affiche une interface premium de réinitialisation du mot de passe",
    "Verify token using the user's old password hash as part of the secret": "Vérifier le jeton en utilisant l'ancien hash du mot de passe de l'utilisateur comme partie du secret",
    "Hash the new password and update": "Hasher le nouveau mot de passe et mettre à jour",
    "Sound assets": "Actifs sonores",
    "Unload previous instance if exists": "Décharger l'instance précédente si elle existe",
    "Auto-cleanup after playback": "Nettoyage automatique après lecture",
    "Add your SF Symbols to Material Icons mappings here.\n * - see Material Icons in the [Icons Directory](https://icons.expo.fyi).\n * - see SF Symbols in the [SF Symbols](https://developer.apple.com/sf-symbols/) app.": "Ajoutez vos correspondances SF Symbols vers Material Icons ici.\n * - voir Material Icons dans le dossier d'icônes [Icons Directory](https://icons.expo.fyi).\n * - voir SF Symbols dans l'application [SF Symbols](https://developer.apple.com/sf-symbols/).",
    "An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.\n * This ensures a consistent look across platforms, and optimal resource usage.\n * Icon `name`s are based on SF Symbols and require manual mapping to Material Icons.": "Un composant d'icône qui utilise les SF Symbols natifs sur iOS, et Material Icons sur Android et le web.\n * Cela garantit un aspect cohérent sur toutes les plateformes et une utilisation optimale des ressources.\n * Les noms d'icônes sont basés sur les SF Symbols et nécessitent une correspondance manuelle vers les Material Icons.",
    "Below are the colors that are used in the app. The colors are defined in the light and dark mode.\n * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.": "Ci-dessous se trouvent les couleurs utilisées dans l'application. Les couleurs sont définies en mode clair et sombre.\n * Il existe de nombreuses autres façons de styliser votre application. Par exemple, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.",
    "Play the message received sound": "Jouer le son de réception de message",
    "Play the notification/announcement sound": "Jouer le son de notification ou d'annonce",
    "This script is used to reset the project to a blank state.\n * It deletes or moves the /app, /components, /hooks, /scripts, and /constants directories to /app-example based on user input and creates a new /app directory with an index.tsx and _layout.tsx file.\n * You can remove the `reset-project` script from package.json and safely delete this file after running it.": "Ce script est utilisé pour réinitialiser le projet à un état vide.\n * Il supprime ou déplace les répertoires /app, /components, /hooks, /scripts, et /constants vers /app-example selon l'entrée utilisateur et crée un nouveau répertoire /app avec un fichier index.tsx et _layout.tsx.\n * Vous pouvez retirer le script `reset-project` de package.json et supprimer ce fichier en toute sécurité après son exécution.",
    "To support static rendering, this value needs to be re-calculated on the client side for web": "Pour supporter le rendu statique, cette valeur doit être recalculée côté client pour le web",
    "1. Check hostUri from expoConfig (Expo Go)": "1. Vérifier l'hostUri depuis expoConfig (Expo Go)",
    "2. Check debuggerHost from expoConfig": "2. Vérifier le debuggerHost depuis expoConfig",
    "3. Check debuggerHost from manifest (older SDKs)": "3. Vérifier le debuggerHost depuis le manifest (anciennes versions de SDK)",
    "4. Check manifest2 (newer SDKs / Expo Go)": "4. Vérifier manifest2 (versions plus récentes de SDK / Expo Go)",
    "Add a soft haptic feedback when pressing down on the tabs.": "Ajouter un retour haptique léger lors de l'appui sur les onglets.",
    "Add response interceptor for automatic retries and token refresh": "Ajouter un intercepteur de réponse pour les tentatives automatiques et le rafraîchissement du token",
    "Adds a consistent premium header block to normal slides.": "Ajoute un en-tête premium standardisé aux diapositives normales.",
    "Abstract summary inside a light gray box table": "Résumé abstrait dans un tableau à fond gris clair",
    "Appends a paragraph to an existing text frame.": "Ajoute un paragraphe à un bloc de texte existant.",
    "Background area": "Zone d'arrière-plan",
    "Badge Coup de coeur inside mockup": "Badge Coup de cœur dans la maquette",
    "Badge favorite heart inside mockup": "Badge cœur de favori dans la maquette",
    "Body rounded block": "Bloc de corps arrondi",
    "Build the document using the Custom Numbered Canvas": "Construire le document en utilisant le canevas numéroté personnalisé",
    "Bullet points inside Q&A or standard lists": "Puces dans les questions-réponses ou listes standard",
    "Card 1: Backend & Prisma": "Carte 1 : Backend & Prisma",
    "Card 2: Mobile Apps (Tenant & Owner)": "Carte 2 : Applications mobiles (Locataire & Propriétaire)",
    "Card 3: Admin Web Panel": "Carte 3 : Panneau web d'administration",
    "Card Header / Image Area placeholder in Light Blue": "En-tête de carte / Espace réservé pour l'image en bleu clair",
    "Check if it's a transient network or proxy error": "Vérifier s'il s'agit d'une erreur réseau ou de proxy temporaire",
    "Class attributes listing": "Liste des attributs de classe",
    "Class title text": "Texte de titre de classe",
    "Color Palette - Sleek Premium Modern Theme": "Palette de couleurs - Thème moderne, épuré et premium",
    "Cover bottom corners of header": "Couvrir les coins inférieurs de l'en-tête",
    "Create _layout.tsx": "Créer _layout.tsx",
    "Create index.tsx": "Créer index.tsx",
    "Create new /app directory": "Créer le nouveau répertoire /app",
    "Create the app-example directory": "Créer le répertoire app-example",
    "Creates a beautiful card container to structure slide content.": "Crée un joli conteneur de carte pour structurer le contenu de la diapositive.",
    "Custom canvas to handle two-pass page numbering and professional footer/header.": "Canevas personnalisé pour gérer la numérotation des pages en deux étapes et l'en-tête/pied de page professionnel.",
    "Custom landscape area: 720 wide, 400 high": "Zone de paysage personnalisée : 720 de large, 400 de haut",
    "Custom styles": "Styles personnalisés",
    "Data dictionary table rows": "Lignes du tableau du dictionnaire de données",
    "Delete the local file after successful upload to free disk space": "Supprimer le fichier local après téléchargement réussi pour libérer de l'espace disque",
    "Determine page size and orientation": "Déterminer la taille et l'orientation de la page",
    "Don't draw headers/footers on page 1 (Cover Page)": "Ne pas dessiner d'en-tête/pied de page sur la page 1 (Page de couverture)",
    "Draw connection lines": "Dessiner les lignes de connexion",
    "Draw connector anchors": "Dessiner les ancrages de connecteurs",
    "Existing Photos": "Photos existantes",
    "Fallback for using MaterialIcons on Android and web.": "Alternative pour utiliser MaterialIcons sur Android et le web.",
    "Fetch fresh properties from backend to ensure photos/details are up-to-date and never disappear!": "Récupérer les propriétés fraîches depuis le backend pour s'assurer que les photos/détails sont à jour et ne disparaissent jamais !",
    "Fetch properties to count them": "Récupérer les propriétés pour les compter",
    "Floating Coup de Cœur badge": "Badge Coup de Cœur flottant",
    "Floating Favorite heart button": "Bouton favori cœur flottant",
    "Floating Image Count badge": "Badge flottant du nombre d'images",
    "Footer Divider Line": "Ligne de séparation du pied de page",
    "Grid lines": "Lignes de grille",
    "Header rounded block": "Bloc arrondi de l'en-tête",
    "Helper to add a standardized text frame.": "Fonction d'aide pour ajouter un bloc de texte standardisé.",
    "Helper to draw beautiful modern rounded cards": "Fonction d'aide pour dessiner de belles cartes arrondies modernes",
    "Labels and Cardinalities": "Étiquettes et cardinalités",
    "Large stylized background element": "Grand élément de fond stylisé",
    "Large vertical accent line": "Grande ligne d'accentuation verticale",
    "Layout coordinate configurations": "Configurations des coordonnées de mise en page",
    "Left Card: Security & Auth": "Carte gauche : Sécurité & Authentification",
    "Left Column (Concept & Tunnel)": "Colonne gauche (Concept & Tunnel)",
    "Left Side text box": "Zone de texte du côté gauche",
    "Left Side: Features List": "Côté gauche : Liste des fonctionnalités",
    "New Photos Preview": "Aperçu des nouvelles photos",
    "New description field": "Nouveau champ de description",
    "Orange 500 (Warm branding orange)": "Orange 500 (Orange de marque chaleureux)",
    "PAGE 1: TITLE/COVER PAGE (Landscape style layout)": "PAGE 1 : PAGE DE COUVERTURE (Mise en page de style paysage)",
    "PAGE 2: THE ER CLASS DIAGRAM (Drawing Canvas Showcase)": "PAGE 2 : DIAGRAMME DE CLASSES ER (Démonstration du canevas de dessin)",
    "PAGE 3: TABLES SPECIFICATIONS REFERENCE (Data Dictionary)": "PAGE 3 : RÉFÉRENCE DES SPÉCIFICATIONS DES TABLES (Dictionnaire de données)",
    "Quick Stats": "Statistiques rapides",
    "Re-run the request": "Relancer la requête",
    "Right Card: Real-Time Visits & Chat": "Carte droite : Visites en temps réel & Chat",
    "Right Column (Network & Retry)": "Colonne droite (Réseau & Tentatives)",
    "Right Side text box - Next Steps": "Zone de texte côté droit - Prochaines étapes",
    "Right Side: Visual Mockup of the Premium Property Card": "Côté droit : Maquette visuelle de la carte de propriété premium",
    "Row 1 (Bottom row - y=20)": "Rangée 1 (Rangée inférieure - y=20)",
    "Row 2 (Middle row - y=150)": "Rangée 2 (Rangée du milieu - y=150)",
    "Row 3 (Top row - y=290)": "Rangée 3 (Rangée supérieure - y=290)",
    "SLIDE 1: COVER SLIDE (Dark Navy Premium Theme)": "DIAPOSITIVE 1 : DIAPOSITIVE DE COUVERTURE (Thème bleu nuit premium)",
    "SLIDE 2: THE 360° ARCHITECTURE OVERVIEW (Light Slide, Multi-Card Layout)": "DIAPOSITIVE 2 : VUE D'ENSEMBLE DE L'ARCHITECTURE 360° (Diapositive claire, mise en page multi-cartes)",
    "SLIDE 3: RESILIENCE & LOCAL TUNNEL AUTOMATION (Light Slide, 2-Column Split Layout)": "DIAPOSITIVE 3 : RÉSILIENCE & AUTOMATISATION DU TUNNEL LOCAL (Diapositive claire, mise en page divisée en 2 colonnes)",
    "SLIDE 4: THE REDESIGNED PREMIUM EXPLORER SCREEN (Visual Feature Showcase)": "DIAPOSITIVE 4 : L'ÉCRAN D'EXPLORATION PREMIUM RECONÇU (Démonstration visuelle des fonctionnalités)",
    "SLIDE 5: OVERFLOW PROTECTION & STABILITY (Technical Layout)": "DIAPOSITIVE 5 : PROTECTION CONTRE LE DÉBORDEMENT & STABILITÉ (Mise en page technique)",
    "SLIDE 6: AUTHENTICATION, VISITS & MODERATION (Summary Slide)": "DIAPOSITIVE 6 : AUTHENTICATION, VISITES & MODÉRATION (Diapositive de résumé)",
    "SLIDE 7: SUMMARY & NEXT STEPS (Dark Navy Divider Theme)": "DIAPOSITIVE 7 : RÉSUMÉ & PROCHAINES ÉTAPES (Thème séparateur bleu nuit)",
    "Save the beautifully crafted presentation": "Sauvegarder la présentation",
    "Sky 100 (Soft background blue)": "Sky 100 (Bleu ciel de fond doux)",
    "Sky 600 (Vibrant active blue)": "Sky 600 (Bleu actif vif)",
    "Slate 200 (Soft grid lines)": "Slate 200 (Lignes de grille douces)",
    "Slate 50 (Very light gray-blue)": "Slate 50 (Gris-bleu très clair)",
    "Slate 500 (Subtle neutral text)": "Slate 500 (Texte neutre subtil)",
    "Slate 900 (Deep modern navy)": "Slate 900 (Bleu nuit moderne profond)",
    "Slide Title": "Titre de la diapositive",
    "Target Landscape layout (11 x 8.5 inches = 792 x 612 pt)": "Mise en page paysage cible (11 x 8.5 pouces = 792 x 612 pt)",
    "Delete local file if it exists and upload failed": "Supprimer le fichier local s'il existe et que le chargement a échoué",
    "10MB limit": "Limite de 10 Mo",
    "Generates the main visual entity relationship class diagram in a ReportLab Drawing.": "Génère le diagramme de classes de relation d'entité visuel principal dans un dessin ReportLab.",
    "Cleanup all loaded sounds (call on unmount)": "Nettoyer tous les sons chargés (appelé lors du démontage du composant)",
    "Configure audio mode for background/silent mode compatibility": "Configurer le mode audio pour la compatibilité avec le mode arrière-plan et silencieux",
    "Play sound only for messages from the other person": "Jouer le son uniquement pour les messages reçus de l'autre personne",
    "Automatically mark all as read when opening notifications": "Marquer automatiquement toutes les notifications comme lues à l'ouverture",
    "Automatically inject JWT token from AsyncStorage into every request if present": "Injecter automatiquement le token JWT de AsyncStorage dans chaque requête si présent",
    "Check for inactivity every 5 seconds": "Vérifier l'inactivité toutes les 5 secondes",
    "If config exists and it's a transient error, initialize/increment retry counter": "Si la configuration existe et qu'il s'agit d'une erreur temporaire, initialiser/incrémenter le compteur de tentatives",
    "Wait before retrying": "Attendre avant de réessayer",
    "Keep user activity updated even when not logged in": "Maintenir l'activité utilisateur à jour même si non connecté",
    "Helper to format property URLs (same as in propertyController)": "Fonction d'aide pour formater les URL de propriétés (comme dans propertyController)",
    "1. Background area": "1. Zone d'arrière-plan",
    "2. Draw Relations (Lines and labels)": "2. Dessiner les relations (lignes et étiquettes)",
    "Labels and Cardinalities": "Étiquettes et cardinalités",
    "Annonce ➔ Bien": "Annonce ➔ Bien",
    "Annonce ➔ Photo": "Annonce ➔ Photo",
    "Annonce ➔ DemandeVisite (angled)": "Annonce ➔ DemandeVisite (incliné)",
    "User ➔ Annonce": "User ➔ Annonce",
    "User ➔ DemandeVisite": "User ➔ DemandeVisite",
    "User ➔ Notification": "User ➔ Notification",
    "User ➔ Conversation (Locataire)": "User ➔ Conversation (Locataire)",
    "Conversation ➔ Message": "Conversation ➔ Message",
    "3 Pillars of Stability": "Les 3 piliers de la stabilité",
    "Left Column (Concept & Tunnel)": "Colonne gauche (Concept & Tunnel)",
    "Right Column (Network & Retry)": "Colonne droite (Réseau & Tentatives)",
    "Category Tag": "Étiquette de catégorie",
    "Badge favorite heart inside mockup": "Badge cœur de favori dans la maquette",
    "Floating Favorite heart button": "Bouton favori cœur flottant",
    "Floating Coup de Cœur badge": "Badge Coup de Cœur flottant",
    "Floating Image Count badge": "Badge flottant du nombre d'images",
    "Badge Coup de coeur inside mockup": "Badge Coup de cœur dans la maquette",
    "Left Side: Features List": "Côté gauche : Liste des fonctionnalités",
    "Right Side: Visual Mockup of the Premium Property Card": "Côté droit : Maquette visuelle de la carte de propriété premium",
    "Business rules state": "État des règles de gestion",
    "Max Active Listings": "Nombre maximum d'annonces actives",
    "Max Photos Per Listing": "Nombre maximum de photos par annonce",
    "Recent Visits & Partners Grid": "Grille des visites récentes & partenaires",
    "Today's metrics": "Métriques du jour",
    "Last 7 days daily stats for graphs": "Statistiques quotidiennes des 7 derniers jours pour les graphiques",
    "Create a notification for all users with the LOCATAIRE role": "Créer une notification pour tous les utilisateurs ayant le rôle LOCATAIRE",
    "Delete photos": "Supprimer les photos",
    "Delete demands of visits": "Supprimer les demandes de visites",
    "Delete the annonce itself": "Supprimer l'annonce elle-même",
    "Delete the associated bien & address": "Supprimer le bien et l'adresse associés",
    "Helper to format property URLs (same as in propertyController)": "Fonction d'aide pour formater les URL de propriétés (comme dans propertyController)",
    "'password' from frontend, mapped to 'motDePasse' in DB": "'password' du frontend, mappé à 'motDePasse' dans la BD",
    "Append token to deep link": "Ajouter le jeton au lien profond",
    "For security, don't disclose that the email does not exist": "Par sécurité, ne pas divulguer que l'email n'existe pas",
    "Token expires in 1 hour. Signed with process.env.JWT_SECRET + user.motDePasse": "Le jeton expire dans 1 heure. Signé avec process.env.JWT_SECRET + user.motDePasse",
    "Renders a premium, stunning UI for resetting password": "Affiche une interface premium de réinitialisation du mot de passe",
    "Verify token using the user's old password hash as part of the secret": "Vérifier le jeton en utilisant l'ancien hash du mot de passe de l'utilisateur comme partie du secret",
    "Hash the new password and update": "Hasher le nouveau mot de passe et mettre à jour",
    "Vérifier l'accès": "Vérifier l'accès",
    "Marquer les messages de l'autre comme lus": "Marquer les messages de l'autre comme lus",
    "Regex to find Python block comments: \"\"\" ... \"\"\" or ''' ... '''": "Regex pour trouver les commentaires de bloc Python : \"\"\" ... \"\"\" ou ''' ... '''",
    "Regex to find Python single-line comments: # ... (avoid matching # inside hex colors like \"#ffffff\")": "Regex pour trouver les commentaires sur une seule ligne Python : # ... (éviter de faire correspondre # dans les couleurs hexadécimales comme \"#ffffff\")",
    "Regex to find block comments: /* ... */": "Regex pour trouver les commentaires de bloc : /* ... */",
    "Regex to find single-line comments: // ... (avoid matching :// for URLs)": "Regex pour trouver les commentaires sur une seule ligne : // ... (éviter de faire correspondre :// pour les URL)",
    "Remove markers to see the actual text": "Supprimer les marqueurs pour voir le texte réel",
    "1. Extract Python block comments": "1. Extraire les commentaires de bloc Python",
    "1. Extract block comments": "1. Extraire les commentaires de bloc",
    "2. Extract Python line comments": "2. Extraire les commentaires de ligne Python",
    "2. Extract line comments": "2. Extraire les commentaires de ligne",
    "Filter out comments that are just delimiters or URLs": "Filtrer les commentaires qui ne sont que des délimiteurs ou des URL",
    "1. Extract Python block comments": "1. Extraire les commentaires de bloc Python",
    "2. Extract Python line comments": "2. Extraire les commentaires de ligne Python",
    "Process line by line to be safe with python comments": "Traiter ligne par ligne pour être sûr avec les commentaires python",
    "Filter directories in-place": "Filtrer les répertoires sur place",
    "Skip files inside ignored directories that os.walk might still visit": "Passer les fichiers dans les répertoires ignorés que os.walk pourrait encore visiter",
    "\"\"\") and text.endswith(\"\"\"": "\"\"\") et text.endswith(\"\"\"",
    "''') and text.endswith('''": "''') et text.endswith('''",
    "\"\"\") and text.endswith(\"\"\"": "\"\"\") et text.endswith(\"\"\"",
    "''') and text.endswith('''": "''') et text.endswith('''",
    "Regex to find block comments: /* ... */": "Regex pour trouver les commentaires de bloc : /* ... */",
    "Regex to find single-line comments: // ... (avoid matching :// for URLs)": "Regex pour trouver les commentaires sur une seule ligne : // ... (éviter de faire correspondre :// pour les URL)",
    "Regex to find Python block comments: \"\"\" ... \"\"\" or ''' ... '''": "Regex pour trouver les commentaires de bloc Python : \"\"\" ... \"\"\" ou ''' ... '''",
    "Regex to find Python single-line comments: # ... (avoid matching # inside hex colors like \"#ffffff\")": "Regex pour trouver les commentaires sur une seule ligne Python : # ... (éviter de faire correspondre # dans les couleurs hexadécimales comme \"#ffffff\")",
    "Remove markers to see the actual text": "Supprimer les marqueurs pour voir le texte réel",
    "1. Extract block comments": "1. Extraire les commentaires de bloc",
    "2. Extract line comments": "2. Extraire les commentaires de ligne",
    "Filter out comments that are just delimiters or URLs": "Filtrer les commentaires qui ne sont que des délimiteurs ou des URL",
    "1. Extract Python block comments": "1. Extraire les commentaires de bloc Python",
    "2. Extract Python line comments": "2. Extraire les commentaires de ligne Python",
    "Process line by line to be safe with python comments": "Traiter ligne par ligne pour être sûr avec les commentaires python",
    "Filter directories in-place": "Filtrer les répertoires sur place",
    "Skip files inside ignored directories that os.walk might still visit": "Passer les fichiers dans les répertoires ignorés que os.walk pourrait encore visiter"
}

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} does not exist.")
        return

    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    count_translated = 0
    count_skipped = 0

    translated_data = {}

    for file_path, comments in data.items():
        translated_list = []
        for comment in comments:
            original_text = comment['text']
            # Find the translation
            translated_text = TRANSLATIONS.get(original_text, original_text)
            
            # If a translation is found and it is different, build the translated raw string
            if translated_text != original_text:
                # Replace the original text inside the raw comment template
                translated_raw = comment['raw'].replace(original_text, translated_text)
                count_translated += 1
            else:
                translated_raw = comment['raw']
                count_skipped += 1
                
            translated_list.append({
                "raw": comment['raw'],
                "text": comment['text'],
                "type": comment['type'],
                "translated_text": translated_text,
                "translated_raw": translated_raw
            })
        translated_data[file_path] = translated_list

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(translated_data, f, ensure_ascii=False, indent=2)

    print(f"Translation mapping complete. Translated {count_translated} comments, skipped {count_skipped} (already French or unchanged).")
    print(f"Results written to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
